### ISSUE TITLE
The install instructions in the README don't work

### ISSUE THREAD

**Issue by retorquere** [guillaumejacquart/stupid-cms-db#3]
After installation, there's no `stupid-cms` command in the path.

**Comment by guillaumejacquart** [comment]
Thanks for your feedback, I'll check it out

**Comment by guillaumejacquart** [comment]
It's fixed now (tested on linux only so far). Thanks again for the feedback @retorquere

**Comment by retorquere** [comment]
On MacOS (which usually behaves the same as Linux as far as Node is concerned), `stupid-cms` is still not found in the path. Did you publish a new version to npm?

**Comment by guillaumejacquart** [comment]
I did publish a new version on npm. I successfully tested on MacOS this morning. But after install, the autcomplete in the terminal was not working, even tough the command was working.
What are your node/npm versions ? How did you install them (using brew or something else) ? can you 'which stupid-cms' ?

**Comment by retorquere** [comment]
I have node 7.3.0, installed through homebrew. After install I have stupid-cms 0.5.0. `which stupid-cms` yields no output.

**Comment by retorquere** [comment]
On [npm](https://www.npmjs.com/package/stupid-cms) I also find 0.5.0. Should I have installed `stupid-cms-db`? I now see that the repo is called `stupid-cms-db` but the README says to install `stupid-cms`.

**Comment by guillaumejacquart** [comment]
Exactly, I will correct it and deprecate the stupid-cms package. stupid-cms was an attempt to have the same features without having a local db.

**Comment by retorquere** [comment]
That did it, thanks.
